
=pod

=encoding utf-8

=head1 NAME

Test::YAFT::Test::More - Test::YAFT for Test::More users

=head1 IMPORT

L<Test::YAFT> exports via L<Exporter::Tiny> providing all benefits such as renaming symbols.

L<Test::YAFT> does not support plan specification via an import statement.

=head1 ASSERTS

=head2 can_ok

Use expectation L<expect_can|Test::YAFT/expect_can>.

	assume q (...)
		=> got    => $package_or_object
		=> expect => expect_can (qw (create retrieve update delete))
		;

=head2 cmp_ok

Use expectation L<expect_compare|Test::YAFT/expect_compare>.

	assume q (...)
		=> got    => $number
		=> expect => expect_compare (q (>=), 0)
		;

See also:
L<expect_number_greater_than|Test::YAFT/expect_number_greater_than>,
L<expect_number_less_than|Test::YAFT/expect_number_less_than>

=head2 fail

Available; also supports an optional parameter C<diag> to show a custom diagnostic message
instead of using the C<fail or diag> pattern.

	fail q (reason);

	fail q (reason)
		=> diag => q (some diagnostic)
		;

=head2 is

Superseded by an assumption expecting a literal value.

	assume q (...)
		=> got    => $value
		=> expect => q (foo)
		;

=head2 is_deeply

Superseded by an assumption expecting a complex data structure.

	assume q (...)
		=> got    => $value
		=> expect => [
			{ a => 1 },
			{ b => 2 },
		];

=head2 isa_ok

Use expectation L<expect_isa|Test::YAFT/expect_isa>.

	assume q (...)
		=> got    => $got
		=> expect => expect_isa (Expected::Class::)
		;

See also:
L<expect_blessed|Test::YAFT/expect_blessed>,
L<expect_blessed_to|Test::YAFT/expect_blessed_to>,
L<expect_instance_of|Test::YAFT/expect_instance_of>

=head2 isnt

Superseded by an assumption expecting the complemented expectation
L<expect_value/Test::Diag/expect_value>.

Available also for data structures (aka C<isnt_deeply>).

	assume q (...)
		=> got    => $got
		=> expect => ! expect_value ($expect)
		;

=head2 like

Superseded by an assumption with the expectation L<expect_like|Test::YAFT/expect_like>.

	assume q (...)
		=> got    => $got
		=> expect => expect_like (qr (...))
		;

=head2 new_ok

Not available; use pattern like:

	my $instance;
	assume q (can create instance)
		=> got    { $instance = $class->new (...) }
		=> expect { expect_instance_of ($class) }
		;

=head2 ok

Available with the L<Test::YAFT> calling interface; see L<ok|Test::YAFT/ok>.

	ok q (...)
		=> got { ... }
		;

=head2 pass

Available with the same name, interface, and behaviour.

=head2 require_ok

Not available; use pattern like:

	assume q (can create instance)
		=> got    { eval "require $package" // die $@ }
		=> expect { expect_true }
		;

=head2 subtest

Available with the same name and interface; in addition, each C<subtest> creates
new L<sub-context|Test::YAFT/Context>.

=head2 unlike

Superseded by an assumption with the complement to the expectation
L<expect_like|Test::YAFT/expect_like>.

	assume q (...)
		=> got    => $got
		=> expect => ! expect_like (qr (...))
		;

=head2 use_ok

Not available; use pattern like:

	assume q (can create instance)
		=> got    { eval "use $package" // die $@ }
		=> expect { expect_true }
		;

=head1 UTILITY FUNCTIONS

=head2 BAIL_OUT

Available as L<bail_out|Test::YAFT/bail_out>.

=head2 diag

Available with the same name, behaviour, and interface.

See: L<diag|Test::YAFT/diag>.

=head2 done_testing

Available with the same name, behaviour, and supporting L<Test::More> interface.

See: L<done_testing|Test::YAFT/done_testing>

=head2 eq_array

Superseded by L<eq_deeply|Test::YAFT/eq_deeply>.

	eq_deeply \ @got, \ @expect;

=head2 eq_hash

Superseded by L<eq_deeply|Test::YAFT/eq_deeply>.

	eq_deeply \ %got, \ %expect;

=head2 eq_set

Superseded by L<eq_deeply|Test::YAFT/eq_deeply> and the expectation L<expect_bag|Test::YAFT/expect_bag>.

	eq_deeply \ @got, expect_bag @expect;

=head2 explain

Available with the same name, interface, and behaviour.

=head2 note

Available with the same name, interface, and behaviour.

=head2 plan

Available with the same name, behaviour, and supporting L<Test::More> interface.

See: L<plan|Test::YAFT/plan>

=head2 skip

Available with the same name, behaviour, and supporting L<Test::More> interface.

See: L<skip|Test::YAFT/skip>

=head2 todo_skip

Available with the same name, behaviour, and supporting L<Test::More> interface.

See: L<todo_skip|Test::YAFT/todo_skip>

=head1 AUTHOR

Branislav Zahradník <barney@cpan.org>

=head1 COPYRIGHT AND LICENSE

This file is part of L<Test::YAFT> distribution.

=cut
