
=pod

=encoding utf-8

=head1 NAME

Test::YAFT::Test::Spec - Test::YAFT for Test::Spec users

=head1 DESCRIPTION

L<Test::YAFT> is also inspired by BDD implemented by L<Test::Spec> / C<rspec>.

Unlike L<Test::Spec>:

=over

=item test case is executed as/when it appears in the source code

=item hierarchical test messages are not concatenated

=back

=head2 after

Not supported. Available only via L<Context::Singleton> context expiration.

=head2 before all

Use L<arrange {}|Test::YAFT/arrange {}> block in a context.

	subtest q (...) => sub {
		arrange { aka_before_all => ... };
	};

=head2 before each

Use L<act {}|Test::YAFT/act {}> in combination with the L<arrange {}|Test::YAFT/arrange {}>
block in an assumption.

=head2 context

Use L<subtest|Test::YAFT/subtest> instead.

=head2 describe

Use L<subtest|Test::YAFT/subtest> instead.

=head1 AUTHOR

Branislav Zahradník <barney@cpan.org>

=head1 COPYRIGHT AND LICENCE

This file is part of L<Test::YAFT> distribution.

=cut
